services:
  traefik-proxy:
    image: ${TRAEFIK_IMAGE}
    container_name: ${TRAEFIK_CONTAINER_NAME}
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - ${DOCKER_SOCK_PATH}:/var/run/docker.sock
      - ${TRAEFIK_CONFIG_PATH}/traefik.toml:/etc/traefik/traefik.toml
      - ${TRAEFIK_ACME_PATH}/acme.json:/acme.json
    restart: always
    networks:
      - network_web

networks:
  network_web:
    external: true